### ISSUE TITLE
Issues with pushing JSON file to repo

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-roles-geekbot-sweep#158]
### Context

The workflows in this repo push the `team-roles.json` file to the `main` branch. These have just recently started failing with a `403` against the `github-actions[bot]` user, even with branch protection rules turned off. I'm not sure what has changed to cause this failure. It could be an upstream change in the `EngBug/add-and-commit` action.

Potential courses of action:

- Monitor `EndBug/add-and-commit` for issues/updates (this is semi-automated by dependabot, but we use a `v9` tag and may need to pin to a specific one for a while as we wait for changes to propagate)
- We can use `actions/checkout` to checkout with a PAT, which will then be consumed by `EndBug/add-and-commit` to do the push. I suspect my handle might not receive a 403 like the bot user does.
- Do nothing. We are currently reevaluating support processes anyway and the bot/rotational nature of the work is likely to be retired.

**Comment by sgibson91** [comment]
As an aside, allowing GitHub Actions to push to protected branches is a sought after feature that is apparently not being prioritised by GitHub right now https://github.com/orgs/community/discussions/25305

**Comment by damianavila** [comment]
>

**Comment by sgibson91** [comment]
@damianavila Ah yes, https://github.com/2i2c-org/infrastructure/issues/359 will be the cause of that
